server:
  port: 3000

spring:
  # 通用的数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://minglifuzhuang.cn:3306/mlcheck?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: abc123

  jpa:
    # 这个参数是在建表的时候，将默认的存储引擎切换为 InnoDB 用的
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #配置在日志中打印出执行的 SQL 语句信息
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update

